name: CI

on:
  push:
    branches:
      - master
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    # TODO: укажите нужные permissions для GITHUB_TOKEN
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # TODO: укажите нужные значения для action setup-java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        run: mvn -B Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
